anuven/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from publications import views
from django.contrib.auth.decorators import login_required
from ubicacion import views as view_ubi
from api import urls as api_urls

urlpatterns = [
    # Examples:
    
    url(r'^accounts/',include('accounts.urls')),
    url(r'^accounts/',include('allauth.urls')),
    url(r'^llenar/',view_ubi.LlenarDB.as_view(), name='llenar'),
    url(r'^terminos/',views.Terminos.as_view(), name='terminos'),
    url(r'^api-auth/',include(api_urls)),
    url(r'^api/',include(api_urls)),
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^anuncio/(?P<slug>[\w-]+)/$',views.PublicacionView.as_view(), name='anuncio'),
    url(r'^anuncio/login/(?P<slug>[\w-]+)/$',views.PublicacionLogin.as_view(), name='anunciologin'),
    url(r'^anuncio/editar/(?P<slug>[\w-]+)/$',views.PublishUpdate.as_view(), name='editar-anuncio'),
    url(r'^anuncios/',include('publications.urls')),
    url(r'^publicar/$', views.PublishForm.as_view(), name='publicar'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^marcas/$',views.BuscarMarcas.as_view(), name='buscarmarcas'),
    url(r'^modelos/$',views.BuscarModelos.as_view(), name='buscarmodelos'),
    url(r'^publicar_images/$',views.PublicarImages, name='publicar_images'),
    url(r'^image/delete/$',views.EliminarImagen.as_view(), name='eliminar_imagen'),
    url(r'^ultimasPublicaciones/',views.Ultimas_publicaciones.as_view(), name='ultimasP'),
    url(r'^publicacionesDestacadas/',views.publicaciones_destacadas.as_view(), name='PDestacadas'),
    url(r'^ciudad/$',view_ubi.BuscarCiudad.as_view(), name='buscarciudad'),
    url(r'^estado/$',view_ubi.BuscarEstado.as_view(), name='buscarestado'),
    url(r'^borrar/(?P<slug>[\w-]+)/$',views.BorrarPublicacion.as_view(), name='borrar-publicacion'),
    url(r'^send-message/$',views.SendMessage, name='send-message'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += url(r'^__debug__/', include(debug_toolbar.urls)),

from django.conf import settings
from django.views.static import serve 
if settings.DEBUG: 
    urlpatterns += [ 
        url(r'^media/(?P<path>.*)$', serve,  {'document_root': settings.MEDIA_ROOT,}), 
    ] 
urlpatterns += [ 
    url(r'^media/(?P<path>.*)$', serve,  {'document_root': settings.MEDIA_ROOT,}), 
    ] 

api/urls.py
from rest_framework import routers
from django.conf.urls import include, url
from api import views
from rest_framework.authtoken import views as auth


router=routers.DefaultRouter()


router.register(r'anuncios',views.DetallesView)
router.register(r'user',views.Register)


urlpatterns = [
	url(r'', include(router.urls)),
	url(r'token-auth2/', views.obtain_auth_token2),
	url(r'token-auth/', auth.obtain_auth_token),
	url(r'upload/$', views.SubirImagen.as_view()),
	#url(r'register/$', views.Register.as_view({'get':'list'})),
]

publications/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from publications import views
from django.contrib.auth.decorators import login_required





urlpatterns = [
	
    url(r'^(?P<estado>[\w-]+)/(?P<categoria>[\w-]+)/(?P<titulo>[\w-]+)/$',views.AnunciosListView.as_view(),name='listado'),
	url(r'^(?P<estado>[\w-]+)/(?P<categoria>[\w-]+)/$',views.AnunciosListView.as_view(),name='listado'),
    url(r'^(?P<estado>[\w-]+)/$',views.AnunciosListView.as_view(),name='listado'),   
    url(r'^$',views.AnunciosListView.as_view(),name='listado'),
    url(r'^publicar/',views.PublishForm.as_view(), name='publicar'),

    #url(r'^editar/(?P<slug>[\w-]+)/$',views.PublishUpdate.as_view(), name='editar'),  
   
    #url(r'^(?P<slug>[\w-]+)/$',views.Templates.as_view(), name='template'),
    
    
    
]

accounts/models.py
# -*- encoding:utf-8 -*-
from __future__ import unicode_literals
from django.template import defaultfilters
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser, AbstractBaseUser
# Create your models here.


class User(AbstractUser):
	telefono=models.CharField(max_length=30)
	telefono2=models.CharField(max_length=30,blank=True,null=True)
	slug = models.SlugField(max_length=100,blank=True,null=True)

	def __unicode__(self):
		return self.email

	def save(self, *args, **kwargs):
		self.slug = self.id
		super(User,self).save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('home')

	class Meta:
		verbose_name = 'Usuario'
		verbose_name_plural = 'Usuarios'


class UserPublication(AbstractBaseUser):
	first_name = models.CharField(max_length=50)
	email = models.EmailField()
	telefono=models.CharField(max_length=30)
	telefono2=models.CharField(max_length=30,blank=True,null=True)
	slug=models.SlugField(max_length=100,blank=True,null=True)
	
	def __unicode__(self):
		return self.email

	def save(self, *args, **kwargs):
		self.slug = defaultfilters.slugify(self.id)
		super(UserPublication,self).save(*args,**kwargs)

	def get_absolute_url(self):
		return reverse('home')

	class Meta:
		verbose_name = 'Usuario de Publicación'
		verbose_name_plural = 'Usuarios de Publicación'

publications/models.py
# -*- encoding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from sorl.thumbnail import ImageField
from accounts.models import User, UserPublication
from django.template import defaultfilters
from django.core.urlresolvers import reverse
from ubicacion.models import Estado, Ciudad
from anuven import settings
# Create your models here.


class Images(models.Model):
	image=ImageField(upload_to='banners')

	def get_images(self):
		if (self.image):
			return '%s%s' % (settings.MEDIA_URL,self.image)
		else:
			return '%s%s' % (settings.STATIC_URL,"image/avatar_default.png")
	class Meta:
		verbose_name = 'Imagen'
		verbose_name_plural = 'Imagenes'
	



class Casas(models.Model):
	metros_construccion = models.IntegerField()
	metros_terreno = models.IntegerField()

class Inmuebles(models.Model):
	metros_construccion = models.IntegerField()

ANIO=[(str(x),x) for x in range(1920,2017)]

class Marca_ayc(models.Model):
	marca=models.CharField(max_length=50)
	def __unicode__(self):
		return self.marca
	class Meta:
		ordering=['marca']
		verbose_name = 'Marca AyC'
		verbose_name_plural = 'Marca AyC'

class Modelo_ayc(models.Model):
	modelo=models.CharField(max_length=50)
	marca=models.ForeignKey(Marca_ayc)

	def __unicode__(self):
		return self.modelo
	class Meta:
		ordering=['modelo']
		verbose_name = 'Modelo AyC'
		verbose_name_plural = 'Modelo AyC'

class Autos_y_Camionetas(models.Model):
	TRANSMISION=(
		('','Seleccione'),
		('0','Manual'),
		('1','Automatica'),
	)
	MARCA_AUTOS=(
		('','Seleccione'),
		('0','Chevrolet'),
	)
	MODELO=(
		('','Seleccione'),
		('0','Camaro'),
	)
	COMBUSTIBLE=(
		('','Seleccione'),
		('0','Gasolina'),
		('1','Diesel'),
		('2','Gas'),
		('3','Electrico'),
		('4','Híbrido'),
	)
	marca = models.ForeignKey(Marca_ayc)
	anio = models.CharField(max_length=4,choices=ANIO)
	transmision = models.CharField(max_length=3,choices=TRANSMISION)
	modelo = models.ForeignKey(Modelo_ayc)
	combustible = models.CharField(max_length=3,choices=COMBUSTIBLE)
	kilometraje = models.IntegerField()

	def __unicode__(self):
		return self.modelo.modelo


class Publicacion(models.Model):
	CATEGORIA=(
		('','---Vehículos---'),
		('AyC','Autos y camionetas'),
		('AyA','Autopartes y Accesorios'),
		('Mot','Motociletas'),
		('CyC','Camiones y Comerciales'),
		('NyA','Náutica y Aviación'),
		('Cas','Casas'),
		('Dep','Departamentos'),
		('TyL','Terrenos y Lotes'),
		('Asi','Asistencias y Cuartos'),
		('CdC','Casas de Campo'),
		('Tra','Traspasos'),
		('RV','Rentas Vacacionales'),
		('Tel','Telefonos'),
		('CyT','Computadoras y Tablets'),
		('ATF','Audio, TV, Fotos y Videos'),
		('CyV','Consolas y Videojuegos'),
		('OE','Otros Electrónicos'),
		('AyM','Animales y Mascotas'),
		('Bic','Bicicleta'),
		('De','Deportes'),
		('IM','Instrumentos Musicales'),
		('CPC','Caza, Pesca y Camping'),
		('HyC','Hobby y Coleccionables'),
		('Lib','Libros'),
		('Bol','Boletos'),
		('VyV','Viajes y Vacaciones'),
		('RyZ','Ropa y Zapatos'),
		('ApN','Articulos para Niños'),
		('AyR','Accesorio y relojes'),
		('SyB','Salud y Belleza'),
		('AA','Amor y Amistad'),
		('Emp','Empleo'),
		('SyE','Servcios y Eventos'),
		('Ele','Electrodomésticos'),
		('MyD','Mueble y Decoracion'),
		('JyE','Jardin y Exterior'),
		('MyC','Maquinaria y Construcción'),
		('ApO','Articulos para la Oficina'),
		('RyC','Restaurantes y Comidas'),
		('Tld','Todo lo demás'),
	)

	PUBLIC_STATUS=(
		('0','Pendiente'),
		('1','Aprobado'),
		('2','Rechazado'),
		('3','Borrador'),
	)

	PART_O_NEG=(
		('PAR','Particular'),
		('NEG','Negocio'),
	)

	CONDICION=(
		('NU','Nuevo'),
		('US','Usado'),
	)
	TIPO=(
		('ve','Venta'),
		('co','Compra'),
		('se','Servicio'),
	)

	user=models.ForeignKey(User,null=True,blank=True)
	userPublication=models.ForeignKey(UserPublication,null=True,blank=True)
	#campos por categoria
	autos_y_camionetas = models.OneToOneField(Autos_y_Camionetas,null=True,  blank=True, related_name='ayc')
	casas = models.OneToOneField(Casas, null=True, blank=True)
	departamentos = models.OneToOneField(Inmuebles,null=True, blank=True)

	#campos comunes
	titulo=models.CharField(max_length=100)
	categoria=models.CharField(choices=CATEGORIA, max_length=3)
	particular_o_negocio=models.CharField(choices=PART_O_NEG,max_length=3)
	descripcion=models.TextField(blank=True)
	precio=models.DecimalField(max_digits=15, decimal_places=2)
	imagenes=models.ManyToManyField(Images, blank=True)
	condicion = models.CharField(choices=CONDICION,max_length=2)
	destacado = models.BooleanField()
	fecha = models.DateTimeField(auto_now_add=True)
	date = models.DateTimeField(auto_now_add=True)
	tipo = models.CharField(max_length=3,choices=TIPO)
	estado=models.ForeignKey(Estado,null=True,blank=True)
	ciudad=models.ForeignKey(Ciudad,null=True,blank=True)

	#campos para otros procesos
	status=models.CharField(choices=PUBLIC_STATUS,max_length=20, default="3")
	slug = models.SlugField(max_length=100,blank=True,null=True)

	def __unicode__(self):
		return self.titulo

	class Meta:
		verbose_name = 'Publicacion'
		verbose_name_plural = 'Publicaciones'

	def get_precio(self):
		return str(self.precio)
	def get_imagen_thumb(self):
		if (self.imagenes.all()):
			print self.imagenes.all()[0].image
			
			return '%s' % (self.imagenes.all()[0].image)
		else:
			return None
	def get_imagen(self):
		if (self.imagenes.all()):
			
			return '%s%s' % (settings.MEDIA_URL,self.imagenes.all()[0].image)
		else:
			return '%s%s' % (settings.STATIC_URL,"image/avatar_default.png")

	def get_absolute_url(self):
		return reverse('property-detail', kwargs={'slug': self.slug})

	def save(self, *args, **kwargs):
		super(Publicacion,self).save(*args,**kwargs)
		self.slug = defaultfilters.slugify(str(self.id)+" "+self.titulo)
		super(Publicacion,self).save(*args,**kwargs)

publications/forms.py
from django import forms
from models import Publicacion, Inmuebles, Casas, Autos_y_Camionetas, Images

class ImagesForm(forms.ModelForm):
	
	images=forms.FileInput()

	def clean_images(self):
		if len(self.cleaned_data['images'])>5:
			raise dforms.ValidationError(_("Limite de imagenes excedido("+str(len(self.request.POST.getlist('images',0)))+" de 5)"))
		return self.cleaned_data

	def save(self,request):
		for img in self.cleaned_data['images']:
			image = models.Images(image=img)
			image.save()
			hotel.images.add(image)
		return super(ImagesForm,self).save(request)

class PublicationForm(forms.ModelForm):
	
	class Meta:
		model=Publicacion
		fields = ['titulo','categoria','particular_o_negocio','descripcion','tipo','precio','condicion','destacado','estado','ciudad']
		widgets = {
			#'precio':forms.TextInput(attrs={'required':True}),
			'name':forms.TextInput(attrs={'id':'inputPropertyFirstName'}),
			'avatar':forms.FileInput(attrs={'id':"input-2",'class':"file",'multiple':"false",'data-show-upload':"true",'data-show-caption':"true"}),
		}

class CasasForm(forms.ModelForm):
	class Meta:
		model=Casas
		fields = ['metros_construccion','metros_terreno']

class InmueblesForm(forms.ModelForm):
	class Meta:
		model=Inmuebles
		fields = ['metros_construccion']

class Autos_y_CamionetasForm(forms.ModelForm):
	class Meta:
		model=Autos_y_Camionetas
		fields = ['marca','anio','transmision','modelo','combustible','kilometraje']
	
	
class ContactForm(forms.Form):
	id_property=forms.IntegerField()
	name=forms.CharField(max_length=30)
	email=forms.EmailField()
	message=forms.CharField(widget=forms.Textarea)

templates/publications/publicacion_confirm_delete.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% load thumbnail %}
	{% block content %}   
		<h2 class="page-header center top-header">Confirmacion para eliminar {{ object }}</h2> <!-- Cambio -->
    	<form class="center" method="post" action=""><!-- Cambio -->
        {% csrf_token %}
        <p>¿Seguro que quieres eliminar el articulo {{ object }}?</p>
        <button type="submit" class="btn btn-danger">Si, eliminar</button>
        <a href="{% url 'editar-anuncio' object.slug %}" class="btn btn-success">Cancelar</a>
    </form>
	{% endblock %}

templates/publications/publicacion_form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
    
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>
<body> hola
<form action="" method="post">
    {% csrf_token %}
   
<label>Titulo</label>
<input id="id_titulo" name="titulo" type="text" value="" placeholder="titulo">
<span id="error_titulo" style="display: none;">* Debe escribir un titulo</span>

<p><label>Categoria:</label> 
<select id="id_categoria" name="categoria">
	<option value="" selected>Seleccione</option>
	<option value="AyC">Autos y Camionetas</option>
</select></p>
<span id="error_categoria" style="display: none;">* Debe seleccionar una categoria</span>

<div id="id_AyC" style="display: none;">
	<label>Marca:</label> 
	<select id="id_Marca_AyC" name="marca">
		<option value="">Seleccione</option>
		{% for id,marca in autos.marca.field.choices %}
		<option value="{{id}}">{{marca}}</option>
		{% endfor %}
	</select>
	<span id="error_marca_AyC" style="display: none;">* Debe seleccionar una marca</span>

	<label>Modelo:</label> 
	<select id="id_Modelo_AyC" name="modelo">
		<option value="">Seleccione</option>
	</select>
</div>

<div><label>Particuloar o negocio</label>
<input id="pot" type="radio" name="particular_o_negocio" value="partiular">
<input id="pot" type="radio" name="particular_o_negocio" value="negocio">
<span id="error_radio" style="display: none;">* Debe seleccionar una opción</span>
</div>

<label>Correo</label>
<input id="id_mail" name="email" value="" placeholder="correo electronico">
<span id="error_mail" style="display: none;">* Debe escribir una direccion de Correo electronico</span>
<span id="error_mail2" style="display: none;">* Debe cumplir este formato: example@email.com</span>

<p><label>Estado:</label> 
<select id="estado" name="estado">
	<option value="" selected>Seleccione</option>

	{% for id,estado in form.estado.field.choices %}
		<option value="{{id}}">{{estado}}</option>
	{% endfor %}
</select></p>
<p><label for="id_ciudad">Ciudad:</label> 

<select id="id_ciudad" name="ciudad">
	<option value="">Seleccione</option>
</select></p>
    <input id="publish" type="submit" value="Submit" />
</form>

<script>
	var val_email = /^[a-zA-Z0-9_\.\-]+@[a-zA-Z0-9_\.\-]+\.[a-zA-Z0-9_\.\-]+$/;
	var campos_cat = "";
	$(document).ready(function(){
		$('#id_Marca_AyC').on('change',modelos_AyC);
		$('#estado').on('change',ciudades);


		$('#id_categoria').on('change', function(){

			var categoria = $('#id_categoria');
			if(categoria.val() == ""){
				$('#error_categoria').fadeIn();
			}else{
				$('#error_categoria').fadeOut();
				
				ocultar_cat();
				mostrar_cat(categoria.val());
			}
			
		});
		$('#pot').on('change',function(){
			rad=$('#pot:checked');
			if(rad.length == 0){
				$('#error_radio').fadeIn();
			}else{
				$('#error_radio').fadeOut();
			}
		});
		$('#id_titulo').on('change',function(){
			var titulo = $('#id_titulo').val();
			if(titulo == ""){
				$('#error_titulo').fadeIn();
			}else{
				$('#error_titulo').fadeOut();
			}

		});
		$('#id_mail').on('change',function(){
			var correo = $('#id_mail').val();
			if(correo == ""){
				$('#error_mail').fadeIn();
				$('#error_mail2').fadeOut();
			}else{
				$('#error_mail').fadeOut();
			
				if(!val_email.test(correo)){
					$('#error_mail2').fadeIn();
				}else{
					$('#error_mail2').fadeOut();
				}
			}
		});

		$('#id_Marca_AyC').on('change',function(){
			var marca = $('#id_Marca_AyC');
			if(marca.val() == ""){
				$('#error_marca_AyC').fadeIn();
			}else{
				$('#error_marca_AyC').fadeOut();
			}				
		});	

		$('#publish').click(function(){
			var titulo = $('#id_titulo').val();
			var categoria = $('#id_categoria');
			var correo = $('#id_mail').val();
			var radio = $('input[type = "radio"]:checked');
			submit = true;

			if(titulo == ""){
				$('#error_titulo').fadeIn();
				submit = false;
			}else{
				$('#error_titulo').fadeOut();
				
			}

			if(correo == ""){
				$('#error_mail').fadeIn();
				$('#error_mail2').fadeOut();
				submit = false;
			}else{
				$('#error_mail').fadeOut();
				
			
				if(!val_email.test(correo)){
					$('#error_mail2').fadeIn();
					submit = false;
				}else{
					$('#error_mail2').fadeOut();
					
				}
			}
			if(radio.length == 0){
				$('#error_radio').fadeIn();
				submit = false;
			}else{
				$('#error_radio').fadeOut();
				
			}

		
			if(categoria.val() == ""){
				$('#error_categoria').fadeIn();
				submit = false;
			}else{
				$('#error_categoria').fadeOut();
				
			}

			switch(campos_cat){
				case 'AyC':
				var marca = $('#id_Marca_AyC');
				if(marca.val() == ""){
					$('#error_marca_AyC').fadeIn();
					submit = false;
				}else{
					$('#error_marca_AyC').fadeOut();
					
				}
				break;
			}

			return submit;

		});


	});

		function mostrar_cat(cat){
			console.log(cat);
			switch(cat){
				case 'AyC':
				$('#id_AyC').fadeIn();
				campos_cat=cat;
				break;
				}
		}

		function ocultar_cat(){
			$('#id_AyC').fadeOut();

		}

		function modelos_AyC(){
			var id = $(this).val();
			if (id!=""){
				$.ajax({
					data : {'id':id},
					url : /modelos/,
					type : 'get',
					success : function(data){
						var html = ""
						for(var i = 0; i<data.length ; i++){
							html += '<option value="'+data[i].fields.id+'">'+data[i].fields.modelo+'</option>'
						}
						$('#id_Modelo_AyC').html(html);
					}

				});
			}else{
				var html = ""
				html += '<option value="">Seleccione</option>'
				$('#id_Modelo_AyC').html(html);
			}
		}
	
		function ciudades(){
			var id = $(this).val();
			if (id!=""){
				$.ajax({
					data : {'id':id},
					url : /ciudad/,
					type : 'get',
					success : function(data){
						var html = ""
						for(var i = 0; i<data.length ; i++){
							html += '<option value="'+data[i].fields.id+'">'+data[i].fields.ciudad+'</option>'
						}
						$('#id_ciudad').html(html);
					}

				});
			}else{
				var html = ""
				html += '<option value="">Seleccione</option>'
				$('#id_ciudad').html(html);
			}
		
		
	
	}
	
</script>



</body>
</html>